### ISSUE TITLE
Jenkins builds failing

### ISSUE THREAD

**Issue by Roadcrosser** [DevotedMC/CivModCore#38]
I wanted to get the 1.16.x versions of this (and other related plugins) off the CI, but each one seems to have failed on `javac: invalid target release: 11`.

I've tried compiling these myself and failing horribly due to not having the exact same dependencies installed.

I'm told JDK 11 should be installed on the CI for the builds to not fail.

**Comment by ProgrammerDan** [comment]
Navigate into the CivClassic builds folder, and use the .jar builds from
the CivModCore in that fork.

**Comment by Roadcrosser** [comment]
Thanks! CivModCore works fine now.

Though I seem to be having issues with other plugins like Citadel. I'll post an issue on that repo in the future when I have more time.
