### ISSUE TITLE
Unsure of database configs

### ISSUE THREAD

**Issue by Roadcrosser** [DevotedMC/CivModCore#39]
I had an [error on Citadel](https://github.com/DevotedMC/Citadel/issues/71) that I managed to trace upstream back to CivModCore. It looks like I needed to uncomment the database lines in the config ~~despite the warning that said `KEEP THIS COMMENTED OUT IN THIS DEFAULT CONFIG OTHERWISE BAD THINGS!`.~~ I now know that that note was meant for the maintainers, not me. Huh.

And yet it seems to work fine now on my test env. I have yet to deploy it though. I'd like to know if this was how I was supposed to do it, since documentation for setup is a bit sparse.

As for the database details, I used the same database and credentials as the namelayer db (and I did the same for Citadel). I'm unsure if I'm supposed to make separate DBs for all three, or if I can just have them all use the same one. Again, without much documentation to see (the VM one I followed only made one DB for namelayer, after all), I'm unsure if this is the correct approach.

**Comment by ProgrammerDan** [comment]
I think that's just a warning to developers not to uncomment in a commit
those lines. However for end users, please configure the database. We
should probably clarify that a bit... :)
